### ISSUE TITLE
annotatr dependencies not loading automatically in Travis CI

### ISSUE THREAD

**Issue by divy-kangeyan** [rcavalcante/annotatr#11]
Hi Raymond,
                     I am using one of the functions in annotatr in my bioconductor package. It works without any problem in my local environment. My package also passes all the builds in the bioconductor multiple platform build. However it is having some errors in Travis CI. This error occurs when generating the vignette of my package. Following is the exact error.

```
Quitting from lines 199-202 (my-vignette.Rmd) 
Error: processing vignette 'my-vignette.Rmd' failed with diagnostics:
The package TxDb.Hsapiens.UCSC.hg38.knownGene is not installed, please install it via Bioconductor.
Execution halted
```

Out of all the packages that I import in mine, `annotatr` is the only one that has `TxDb.Hsapiens.UCSC.hg38.knownGene` as a dependency. Shouldn't the dependencies of the packages that I import automatically loaded in the environment? 

I am wondering if you have encountered this issue previously when importing annotatr.

Thank you,
Divy

**Comment by rcavalcante** [comment]
Hi Divy,

From looking at your Travis logs (https://travis-ci.org/aryeelab/scmeth/jobs/361024757) I can see that the suggested packages from annotatr’s DESCRIPTION are not installed, but scmeth’s suggested packages are. That tells me that Travis doesn’t traverse into dependency package suggested packages. As an aside, I’d bet that TxDb.Hsapiens.UCSC.hg38.knownGene is installed on your local environment, and that the Bioc builds have access to everything within Bioc.

One thing you could try, since you need TxDb.Hsapiens.UCSC.hg38.knownGene in the vignette, is to add it to scmeth’s Suggests: and see if the error disappears.

If that doesn’t fix it, I can try thinking of other solutions.

Best,
Raymond

**Comment by divy-kangeyan** [comment]
Hi Raymond,
                      I added the `TxDb.Hsapiens.UCSC.hg38.knownGene` package to the suggests section. Then I also had to add `org.Hs.eg.db`. After adding those two packages the travis build succeeded. I also experienced similar problem in a cloud environment where I had to load the two packages above explicitly. Do you have a sense why this is the case, it seems for other bioconductor packages, their dependencies are loaded automatically.

Thank you,
Divy

**Comment by rcavalcante** [comment]
Hi Divy,
My understanding is that Suggested packages are not loaded automatically. I recently changed those packages to Suggested because I received a couple comments that it's a waste of space to require everyone to install the packages for genomes that they may not ever use. The downside is that users need to be more proactive about making sure the species specific Suggested packages are installed to use annotatr for those species.

Put another way, if a part of your vignette was written such that it needed a Suggested package from another dependency that also wasn't a Depends: of any other dependency, then you would have this same problem.

Thanks,
Raymond

**Comment by rcavalcante** [comment]
Hi Divy,

In an ideal world the Txdb objects that I use to create the annotations as well as the CpG island tracks would be in the AnnotationHub package instead of needing the individual Txdb packages. That way it'd be easier to add new species and genome builds on the fly, but AnnotationHub is ... sort of frustrating and doesn't contain all the things you'd expect.

I've been wanting to rethink species / genome build support for a little while, so I'll start to prioritize that. For now, are you interested in me adding `Scerevisiae`?

Thanks, 
Raymond
