### ISSUE TITLE
summarize_annotations gives 'duplicate row.names' error

### ISSUE THREAD

**Issue by kdkorthauer** [rcavalcante/annotatr#4]
Hello,

I have successfully (I think) used the `annotate_regions` function to add CpG location category annotations (using the 'hg38_cpgs' shortcut in the `build_annotations` function) to regions of interest. Now I am trying to use the `summarize_annotations` function to count how many regions were in islands, shelves, shores, and open sea. However, this throws an error: 
>"Error in data.frame(seqnames = as.factor(seqnames(x)), start = start(x),  : 
  duplicate row.names: 107641, 63635, 88662, 115649, ..."

I am using the following code. The GRanges object that contains my regions of interest is `dmrs`, and the error is thrown after the last line (call to `summarize_annotations`).

```
   annotations = build_annotations(genome = 'hg38', annotations = 'hg38_cpgs')
   dm_annotated = annotate_regions(regions = dmrs,
   	annotations = annotations,
   	ignore.strand = TRUE,
   	quiet = FALSE)
   dm_annsum = summarize_annotations(
	   annotated_regions = dm_annotated,
	   quiet = TRUE)
```

Could this be due to the fact that some of the regions map to multiple categories (e.g. part of a region overlaps a shelf and another part of the same region overlaps a shore)? This is my best guess from the error message and the fact that if I stick the line `dm_annotated = unique(dm_annotated)` it runs fine. However, it seems from the documentation that duplicates such as these should be fine. 

I'd appreciate any insight you might have on this.

Best,
Keegan

**Comment by kdkorthauer** [comment]
On a related note, once this is resolved, instead of counting the regions that overlap with multiple categories twice, I'd be interested in counting them only once. The category to count could be just the category that had the largest overlap with the region of interest. If you have any suggestions on how to do this with the `annotatr` functions please let me know. Or perhaps you could consider adding this a feature in the future if you think it might be useful to others.

**Comment by rcavalcante** [comment]
Good afternoon,

Thanks for catching this bug. It turns out that coercing a `GRanges` to a `data.frame` can result in duplicate `row.names`, so I just need to make sure all instances use `row.names = NULL` to avoid that problem. 

Unfortunately, commits to `release-3.4` are no longer being accepted because of the impending release of Bioconductor 3.5, so I have updated the devel version and it'll rollover into the release (as `v1.2.0`) in a week or so. For now, you can do `devtools::install_github('rcavalcante/annotatr')`. The Travis Build is quite slow right now, causing it to timeout and fail, but it builds fine locally...

Regarding your follow up, your point is well taken. I envision two ways for you to deal with that.

1. You can use the `minoverlap` parameter of `annotate_regions()` to try to capture the longer overlaps, but that's probably not always going to get you exactly what you want...
2. Assuming your input regions have names in a column called `name`:
```
# Add a GRanges to the mcols giving the intersection
dm_annotated$intersection = GenomicRanges::GRanges(
	seqnames = GenomicRanges::seqnames(dm_annotated),
	ranges = IRanges::IRanges(
		start = pmax(start(dm_annotated), start(dm_annotated$annot)),
		end = pmin(end(dm_annotated), end(dm_annotated$annot))
	),
	strand = strand(dm_annotated)
)

# Take the width of the intersections
dm_annotated$overlapWidth = width(dm_annotated$intersection)

# Split by the name of the input regions (create a name column after
# read_regions() if the input regions aren't named)
dm_annotated_grl = split(dm_annotated, dm_annotated$name)

# Doing this is super slow, but I'm not sure of a faster way to do it...
dm_annotated_grl = S4Vectors::endoapply(dm_annotated_grl, function(regions){
	max_width = max(regions$overlapWidth)
	max_idx = which(regions$overlapWidth == max_width)

	if(length(max_idx) > 1) {
		return(regions[sample(max_idx, 1)])
	} else {
		return(regions[max_idx])
	}
})

dm_annotated_restricted = unlist(dm_annotated_grl, use.names = FALSE)
```

**Comment by kdkorthauer** [comment]
Awesome, thanks for looking into this so quickly. I'll get the release version once it's out.  In the meantime, I've just manually extracted and counted the annotation types (island, shore, shelf, inter) from the `dm_annotated` object.  

Many thanks also for the suggestion to compare intersection widths of the duplicates; I'll give it a try!

Best,
Keegan
