### ISSUE TITLE
lncRNA link not working

### ISSUE THREAD

**Issue by AlejRSosa** [rcavalcante/annotatr#48]
Hello, I don't know if this project is still being updated or not, but I was trying to annotate my DMRs using annotatr and even though most of the annotations that I wanted are working, the one for hg19_lncrna_gencode is throwing an error as it is not finding the URL.

It is currently trying to find the information from 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.long_noncoding_RNAs.gtf.gz' and since this leads to an empty page, it is not working anymore. 

I have managed to download the .gz file from https://www.gencodegenes.org/human/release_19.html and I thought I could perhaps make a custom annotation but I am not managing. What I have tried is this:

```
> data.file <- '/home/alejandrarodrigu21/Downloads/gencode.v19.long_noncoding_RNAs.gtf.gz'
> read_annotations(data.file, name='lncRNA', genome='hg19')
Error in .local(con, format, text, ...) : 
  unused argument (extraCols = character(0))
```
But I do not understand what the error is - I am not that fluent in R yet. I have also tried this:
```
annotationgr = build_annotations(genome='hg19', annotations='/home/alejandrarodrigu21/Downloads/gencode.v19.long_noncoding_RNAs.gtf.gz')
Error: ‘/home/alejandrarodrigu21/Downloads/gencode.v19.long_noncoding_RNAs.gtf.gz’ not in annotatr_cache
```
Could anyone help me with this?
Thanks,
Alejandra

**Comment by rcavalcante** [comment]
Hi,

Apologies for the very late reply. I think the lncRNA resource error might have been transient (not dissimilar to Issue #49). I was able to
```
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.long_noncoding_RNAs.gtf.gz
```
just now, and I was able to build all the hg19 resources that are built-in with
```
annot <- builtin_annotations()[grep("hg19", builtin_annotations())]
annotations <- build_annotations(genome = 'hg19', annotations = annot)
```
Have you, since you created the issue, been able to retrieve the lncRNA annotation that's built-in?

As to your other question about getting the file yourself, and the error you get about the unused `extraCols` argument, I am somewhat perplexed at the moment. On a lark, I grabbed a BED file of mouse enhancers and did
```
read_annotations('~/Downloads/mouse_permissive_enhancers_phase_1_and_2.bed.gz', name = 'test', genome = 'mm10')
```
which worked, but then when I tried the GTF file I got the same error as you.

So I think the issue is that the `extraCols` parameter isn't used in the subsequent function calls used for the GTF, but is for the BED. I'll have to figure out how to deal with this, so thanks for surfacing this issue.

With that said, please do check if the lncRNA resource issue was transient, and let me know.

Thanks,
Raymond

**Comment by crazysummerW** [comment]
hi, @rcavalcante 
I got the same Error:
`Building lncRNA transcripts...
trying URL 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.long_noncoding_RNAs.gtf.gz'
Content type 'unknown' length 2330848 bytes (2.2 MB)
=============================
Error in download.file(resource(con), destfile) :
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.long_noncoding_RNAs.gtf.gz'
`
Then, I downloaded it. But  I got the same error:
`read_annotations('gencode.v19.long_noncoding_RNAs.gtf.gz', name = 'test', genome = 'hg19')

Error in .local(con, format, text, ...) :
  unused argument (extraCols = character(0))
`
Could you help me ?

**Comment by rcavalcante** [comment]
In the end, all annotatr truly needs for a set of annotations is a GenomicRanges object with some particular columns.

- id: a unique identifier per annotaiton, of your choice if you like
- tx_id: a transcript ID of some sort
- gene_id: a gene ID of some sort (Entrez, RefSeq, ENSEMBL, etc)
- symbol: a gene symbol of some kind
- type: of the form {genome}_{class}_{type}, e.g. mm10_cpg_island

tx_id, gene_id, and symbol are all optional (i.e. they can be NA).

**Comment by rcavalcante** [comment]
FWIW, all the lncRNA built-ins seem to be working fine.
