### ISSUE TITLE
read regions of interest into R

### ISSUE THREAD

**Issue by ale07alvarez** [rcavalcante/annotatr#6]
Please excuse my lack of understanding annotatr, I have three genomic regions I would like to annotate, (intersect with available genomic features ) and I don't know how to read the regions into R. The Paper mentions the use of readr::read_csv() but the R tutorial does not show an example. Could you please let me know how I can read regions of interest for use with annotatr annotation tools. 
In my case, the regions I'm interested in are just genes and the regions 500kb around each gene, I do not have a score (p-value) but simple coordinates for the region.
Thank you!

**Comment by rcavalcante** [comment]
Hello,

Thanks for your interest in annotatr. Please see the documentation on Bioconductor for the most up to date description of which functions to use.

http://bioconductor.org/packages/release/bioc/vignettes/annotatr/inst/doc/annotatr-vignette.html#reading-genomic-regions

Please let me know if you have other questions.

Thanks,
Raymond

**Comment by ale07alvarez** [comment]
That for your reply, I of course have looked at this tutorial but I have a very specific question. I would very much appreciate an answer to my question.
Thanks!

**Comment by rcavalcante** [comment]
I'm sorry, I think you're referencing a previous version of the paper as it appears in the bioRxiv (http://www.biorxiv.org/content/early/2016/02/15/039685.full.pdf+html). The paper was revised since that first preprint and published in Bioinformatics earlier this year (http://dx.doi.org/10.1093/bioinformatics/btx183). In addition to changes in the paper, the package was changed during the Bioconductor submission process. One of those changes includes using rtracklayer::import() in the read_regions() function instead of readr::read_tsv() function. 

I understand your question to be, "How do I read regions into annotatr?" The read_regions() function should be used to read the file containing the regions. Have your tried using the function and encountered an error?

I'm sorry if I'm misunderstanding your question.

**Comment by rcavalcante** [comment]
To follow up on this, if your regions are just coordinates, like in a BED3 file, e.g.
```
chr1	100	200
chr2	500	600
chr8	300	350
```
Then it might be easiest to make sure the filename ends in `.bed` and you can read it in with:
```
regions = read_regions(con = '/path/to/foo.bed', genome = 'hg19')
```
If you do `?read_regions` you will see a lot more options, but for a simple `.bed` file you can get away with this minimal command. 

If your file ends in something other than `.bed`, then you should use the `format = 'bed'` option.

**Comment by ale07alvarez** [comment]
Yes my regions are in BED3 
This is how you read your regions 
#---------------------------------------
dm_file = system.file('extdata', 'IDH2mut_v_NBM_multi_data_chr9.txt.gz', package = 'annotatr')
extraCols = c(diff_meth = 'numeric', mu0 = 'numeric', mu1 = 'numeric')
dm_regions = read_regions(con = dm_file, genome = 'hg19', extraCols = extraCols, format = 'bed',
                          rename_name = 'DM_status', rename_score = 'pval')

#---------------------------------------

could I replace all that code with:
dm_regions = read_regions(con = "regions.bed", genome = 'hg19’)
Thank you so much for your help!
Alejandra

**Comment by ale07alvarez** [comment]
I’m very sorry for the multiple emails but I also encountered this error when running the example code and also when using my regions as read using the 
> dm_regions = read_regions(con = "regions.bed", genome = 'hg19’)


dm_random_regions = randomize_regions(
+   regions = dm_regions,
+   allow.overlaps = TRUE,
+   per.chromosome = TRUE)
Error in function (type, msg, asError = TRUE)  : 
  Operation timed out after 300564 milliseconds with 0 out of 0 bytes received

When I was testing the example code I just skipped this part and continue to run the rest of the code and it worked fine, all the plots were created.
Please let me know how I can fix this error.
Thank you so much!
Alejandra

**Comment by rcavalcante** [comment]
Hello,

I apologize for the delay in responding. The `randomize_regions()` function is unfortunately quite unreliable because of a dependency that requires fetching remote data. Have you been able to try it again?

However, if you only have 3 regions that you're annotating (as mentioned in the initial message), perhaps random regions isn't appropriate.

Thanks,
Raymond
