### ISSUE TITLE
Error message by plot_categorical

### ISSUE THREAD

**Issue by xie186** [rcavalcante/annotatr#9]
Hi there, 
Thanks for developing `annotatr`. 
I encountered the warnings when using `plot_categorical`. 
`Warning message:
In subset_order_tbl(tbl = annotated_regions, col = fill, col_order = fill_order) :
  There are elements in col_order that are not present in the corresponding column. Check for typos, or this could be a result of 0 tallies.`

Then I got the error message as below:
`Error in seq.default(h[1], h[2], length.out = n) : 
  'to' must be a finite number`. 

`
$ table(df_dm_annotated[df_dm_annotated$DM_status=="hypo", ]$annot.type)

  mm10_cpg_inter mm10_cpg_islands mm10_cpg_shelves  mm10_cpg_shores 
            1566               12              147              458 
$ table(df_dm_annotated[df_dm_annotated$DM_status=="hyper", ]$annot.type)

  mm10_cpg_inter mm10_cpg_islands mm10_cpg_shelves  mm10_cpg_shores 
             538               25               55              151 
$ table(df_dm_annotated[df_dm_annotated$DM_status !="hyper" & df_dm_annotated$DM_status!="hyper", ]$annot.type)

$ table(df_dm_annotated[df_dm_annotated$DM_status !="hypo" & df_dm_annotated$DM_status!="hyper", ]$annot.type)

  mm10_cpg_inter mm10_cpg_islands mm10_cpg_shelves  mm10_cpg_shores 
          259318            25014            22412           104207 
`

Could you help me on this problem? Thanks.

**Comment by rcavalcante** [comment]
Hello, I'd be happy to help. Could you please include the data you used that got to this error, and the preceding code that led up to it? Also the `devtools::session_info()` for the session in which you got the error would be helpful.

That way I'll be able to recreate the problem and troubleshoot it.

Thanks.

**Comment by xie186** [comment]
Now it's working. I updated to the latest version. ?Thanks.

________________________________

**Comment by rcavalcante** [comment]
Ah, well that makes both of our lives easier. Thanks.

**Comment by framas15** [comment]
Hi,
I got the same error when using plot_annotation():
In subset_order_tbl(tbl = annotated_regions, col = "annot.type",  :
There are elements in col_order that are not present in the corresponding column. Check for typos, or this could be a result of 0 tallies.
Do you have any idea what is going wrong? 

Thank you!

This is my session info:

- Session info ----------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.1.0 (2021-05-18)
 os       Windows 10 x64 (build 18363)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Sweden.1252
 ctype    English_Sweden.1252
 tz       Europe/Berlin
 date     2021-12-16
 rstudio  1.4.1717 Juliet Rose (desktop)
 pandoc   2.11.4 @ C:/Program Files/RStudio/bin/pandoc/ (via rmarkdown)

- Packages --------------------------------------------------------------------------------------------------------------
 package                           * version  date (UTC) lib source
 AnnotationDbi                     * 1.54.1   2021-06-08 [1] Bioconductor
 AnnotationHub                       3.0.2    2021-10-14 [1] Bioconductor
 annotatr                          * 1.18.1   2021-07-13 [1] Bioconductor
 assertthat                          0.2.1    2019-03-21 [1] CRAN (R 4.1.0)
 Biobase                           * 2.52.0   2021-05-19 [1] Bioconductor
 BiocFileCache                       2.0.0    2021-05-19 [1] Bioconductor
 BiocGenerics                      * 0.38.0   2021-05-19 [1] Bioconductor
 BiocIO                              1.2.0    2021-05-19 [1] Bioconductor
 BiocManager                         1.30.16  2021-06-15 [1] CRAN (R 4.1.0)
 BiocParallel                        1.26.2   2021-08-22 [1] Bioconductor
 BiocVersion                         3.13.1   2021-03-08 [1] Bioconductor
 biomaRt                             2.48.3   2021-08-17 [1] Bioconductor
 Biostrings                          2.60.2   2021-08-05 [1] Bioconductor
 bit                                 4.0.4    2020-08-04 [1] CRAN (R 4.1.0)
 bit64                               4.0.5    2020-08-30 [1] CRAN (R 4.1.0)
 bitops                              1.0-7    2021-04-24 [1] CRAN (R 4.1.0)
 blob                                1.2.2    2021-07-23 [1] CRAN (R 4.1.1)
 BSgenome                            1.60.0   2021-05-19 [1] Bioconductor
 cachem                              1.0.6    2021-08-19 [1] CRAN (R 4.1.2)
 callr                               3.7.0    2021-04-20 [1] CRAN (R 4.1.0)
 cli                                 3.1.0    2021-10-27 [1] CRAN (R 4.1.1)
 colorspace                          2.0-2    2021-06-24 [1] CRAN (R 4.1.0)
 crayon                              1.4.2    2021-10-29 [1] CRAN (R 4.1.1)
 curl                                4.3.2    2021-06-23 [1] CRAN (R 4.1.0)
 DBI                                 1.1.1    2021-01-15 [1] CRAN (R 4.1.0)
 dbplyr                              2.1.1    2021-04-06 [1] CRAN (R 4.1.0)
 DelayedArray                        0.18.0   2021-05-19 [1] Bioconductor
 desc                                1.4.0    2021-09-28 [1] CRAN (R 4.1.2)
 devtools                            2.4.3    2021-11-30 [1] CRAN (R 4.1.2)
 digest                              0.6.27   2020-10-24 [1] CRAN (R 4.1.0)
 dplyr                               1.0.7    2021-06-18 [1] CRAN (R 4.1.0)
 ellipsis                            0.3.2    2021-04-29 [1] CRAN (R 4.1.0)
 evaluate                            0.14     2019-05-28 [1] CRAN (R 4.1.0)
 fansi                               0.5.0    2021-05-25 [1] CRAN (R 4.1.0)
 farver                              2.1.0    2021-02-28 [1] CRAN (R 4.1.0)
 fastmap                             1.1.0    2021-01-25 [1] CRAN (R 4.1.0)
 filelock                            1.0.2    2018-10-05 [1] CRAN (R 4.1.0)
 fs                                  1.5.2    2021-12-08 [1] CRAN (R 4.1.2)
 generics                            0.1.1    2021-10-25 [1] CRAN (R 4.1.1)
 GenomeInfoDb                      * 1.28.4   2021-09-09 [1] Bioconductor
 GenomeInfoDbData                    1.2.6    2021-07-15 [1] Bioconductor
 GenomicAlignments                   1.28.0   2021-05-19 [1] Bioconductor
 GenomicFeatures                   * 1.44.2   2021-08-26 [1] Bioconductor
 GenomicRanges                     * 1.44.0   2021-05-19 [1] Bioconductor
 ggplot2                             3.3.5    2021-06-25 [1] CRAN (R 4.1.0)
 glue                                1.4.2    2020-08-27 [1] CRAN (R 4.1.0)
 gtable                              0.3.0    2019-03-25 [1] CRAN (R 4.1.0)
 hms                                 1.1.1    2021-09-26 [1] CRAN (R 4.1.1)
 htmltools                           0.5.2    2021-08-25 [1] CRAN (R 4.1.1)
 httpuv                              1.6.4    2021-12-14 [1] CRAN (R 4.1.2)
 httr                                1.4.2    2020-07-20 [1] CRAN (R 4.1.0)
 interactiveDisplayBase              1.30.0   2021-05-19 [1] Bioconductor
 IRanges                           * 2.26.0   2021-05-19 [1] Bioconductor
 KEGGREST                            1.32.0   2021-05-19 [1] Bioconductor
 knitr                               1.36     2021-09-29 [1] CRAN (R 4.1.1)
 labeling                            0.4.2    2020-10-20 [1] CRAN (R 4.1.0)
 later                               1.3.0    2021-08-18 [1] CRAN (R 4.1.1)
 lattice                             0.20-44  2021-05-02 [2] CRAN (R 4.1.0)
 lifecycle                           1.0.1    2021-09-24 [1] CRAN (R 4.1.1)
 magrittr                            2.0.1    2020-11-17 [1] CRAN (R 4.1.0)
 Matrix                              1.3-3    2021-05-04 [2] CRAN (R 4.1.0)
 MatrixGenerics                      1.4.3    2021-08-26 [1] Bioconductor
 matrixStats                         0.61.0   2021-09-17 [1] CRAN (R 4.1.1)
 memoise                             2.0.1    2021-11-26 [1] CRAN (R 4.1.2)
 mime                                0.12     2021-09-28 [1] CRAN (R 4.1.1)
 munsell                             0.5.0    2018-06-12 [1] CRAN (R 4.1.0)
 org.Hs.eg.db                      * 3.13.0   2021-11-08 [1] Bioconductor
 pillar                              1.6.4    2021-10-18 [1] CRAN (R 4.1.1)
 pkgbuild                            1.3.0    2021-12-09 [1] CRAN (R 4.1.2)
 pkgconfig                           2.0.3    2019-09-22 [1] CRAN (R 4.1.0)
 pkgload                             1.2.4    2021-11-30 [1] CRAN (R 4.1.2)
 plyr                                1.8.6    2020-03-03 [1] CRAN (R 4.1.0)
 png                                 0.1-7    2013-12-03 [1] CRAN (R 4.1.0)
 prettyunits                         1.1.1    2020-01-24 [1] CRAN (R 4.1.0)
 processx                            3.5.2    2021-04-30 [1] CRAN (R 4.1.0)
 progress                            1.2.2    2019-05-16 [1] CRAN (R 4.1.0)
 promises                            1.2.0.1  2021-02-11 [1] CRAN (R 4.1.1)
 ps                                  1.6.0    2021-02-28 [1] CRAN (R 4.1.0)
 purrr                               0.3.4    2020-04-17 [1] CRAN (R 4.1.0)
 R6                                  2.5.1    2021-08-19 [1] CRAN (R 4.1.1)
 rappdirs                            0.3.3    2021-01-31 [1] CRAN (R 4.1.0)
 Rcpp                                1.0.7    2021-07-07 [1] CRAN (R 4.1.0)
 RCurl                               1.98-1.5 2021-09-17 [1] CRAN (R 4.1.1)
 readr                               2.1.1    2021-11-30 [1] CRAN (R 4.1.2)
 regioneR                          * 1.24.0   2021-05-19 [1] Bioconductor
 remotes                             2.4.2    2021-11-30 [1] CRAN (R 4.1.2)
 reshape2                            1.4.4    2020-04-09 [1] CRAN (R 4.1.0)
 restfulr                            0.0.13   2017-08-06 [1] CRAN (R 4.1.0)
 rjson                               0.2.20   2018-06-08 [1] CRAN (R 4.1.0)
 rlang                               0.4.11   2021-04-30 [1] CRAN (R 4.1.0)
 rmarkdown                           2.11     2021-09-14 [1] CRAN (R 4.1.1)
 rprojroot                           2.0.2    2020-11-15 [1] CRAN (R 4.1.2)
 Rsamtools                           2.8.0    2021-05-19 [1] Bioconductor
 RSQLite                             2.2.9    2021-12-06 [1] CRAN (R 4.1.2)
 rstudioapi                          0.13     2020-11-12 [1] CRAN (R 4.1.0)
 rtracklayer                         1.52.1   2021-08-15 [1] Bioconductor
 S4Vectors                         * 0.30.2   2021-10-03 [1] Bioconductor
 scales                              1.1.1    2020-05-11 [1] CRAN (R 4.1.0)
 sessioninfo                         1.2.2    2021-12-06 [1] CRAN (R 4.1.2)
 shiny                               1.7.1    2021-10-02 [1] CRAN (R 4.1.1)
 stringi                             1.7.6    2021-11-29 [1] CRAN (R 4.1.2)
 stringr                             1.4.0    2019-02-10 [1] CRAN (R 4.1.0)
 SummarizedExperiment                1.22.0   2021-05-19 [1] Bioconductor
 testthat                            3.1.1    2021-12-03 [1] CRAN (R 4.1.2)
 tibble                              3.1.2    2021-05-16 [1] CRAN (R 4.1.0)
 tidyselect                          1.1.1    2021-04-30 [1] CRAN (R 4.1.0)
 TxDb.Hsapiens.UCSC.hg19.knownGene * 3.2.2    2021-12-15 [1] Bioconductor
 tzdb                                0.2.0    2021-10-27 [1] CRAN (R 4.1.1)
 usethis                             2.1.5    2021-12-09 [1] CRAN (R 4.1.2)
 utf8                                1.2.1    2021-03-12 [1] CRAN (R 4.1.0)
 vctrs                               0.3.8    2021-04-29 [1] CRAN (R 4.1.0)
 withr                               2.4.3    2021-11-30 [1] CRAN (R 4.1.2)
 xfun                                0.27     2021-10-18 [1] CRAN (R 4.1.1)
 XML                                 3.99-0.8 2021-09-17 [1] CRAN (R 4.1.1)
 xml2                                1.3.3    2021-11-30 [1] CRAN (R 4.1.2)
 xtable                              1.8-4    2019-04-21 [1] CRAN (R 4.1.0)
 XVector                             0.32.0   2021-05-19 [1] Bioconductor
 yaml                                2.2.1    2020-02-01 [1] CRAN (R 4.1.0)
 zlibbioc                            1.38.0   2021-05-19 [1] Bioconductor

**Comment by rcavalcante** [comment]
Hi @framas15 ,

First thing that comes to mind is to see if it occurs on the current version of Bioconductor. Second thing is, can you provide an example of how you arrive at this error? Since the previous issue submitter updated Bioconductor and it solved there problem, we never got to the point of actually figuring out what was causing the problem.

Thanks,
Raymond

**Comment by framas15** [comment]
Dear Raymond,
Thanks for the answer.

I have now updated Bioconductor to the 3.14 version (BiocManager 1.30.16), and this is the session info now:
> devtools::session_info()
- Session info ----------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.1.0 (2021-05-18)
 os       Windows 10 x64 (build 18363)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Sweden.1252
 ctype    English_Sweden.1252
 tz       Europe/Berlin
 date     2021-12-20
 rstudio  1.4.1717 Juliet Rose (desktop)
 pandoc   2.11.4 @ C:/Program Files/RStudio/bin/pandoc/ (via rmarkdown)

- Packages --------------------------------------------------------------------------------------------------------------
 package     * version date (UTC) lib source
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
 BiocManager   1.30.16 2021-06-15 [1] CRAN (R 4.1.0)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.2)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.0)
 cli           3.1.0   2021-10-27 [1] CRAN (R 4.1.1)
 crayon        1.4.2   2021-10-29 [1] CRAN (R 4.1.1)
 DBI           1.1.2   2021-12-20 [1] CRAN (R 4.1.0)
 desc          1.4.0   2021-09-28 [1] CRAN (R 4.1.2)
 devtools      2.4.3   2021-11-30 [1] CRAN (R 4.1.2)
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.1.0)
 dplyr         1.0.7   2021-06-18 [1] CRAN (R 4.1.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
 generics      0.1.1   2021-10-25 [1] CRAN (R 4.1.1)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
 htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
 knitr         1.37    2021-12-16 [1] CRAN (R 4.1.2)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.1.2)
 pillar        1.6.4   2021-10-18 [1] CRAN (R 4.1.1)
 pkgbuild      1.3.0   2021-12-09 [1] CRAN (R 4.1.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 pkgload       1.2.4   2021-11-30 [1] CRAN (R 4.1.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.0)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.1.2)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
 rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.1)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.2)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.2)
 testthat      3.1.1   2021-12-03 [1] CRAN (R 4.1.2)
 tibble        3.1.2   2021-05-16 [1] CRAN (R 4.1.0)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.1.0)
 usethis       2.1.5   2021-12-09 [1] CRAN (R 4.1.2)
 utf8          1.2.1   2021-03-12 [1] CRAN (R 4.1.0)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
 withr         2.4.3   2021-11-30 [1] CRAN (R 4.1.2)
 xfun          0.27    2021-10-18 [1] CRAN (R 4.1.1)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)

 [1] C:/Users/framas/R/win-library/4.1
 [2] C:/Program Files/R/R-4.1.0/library

The code I used until I got the error is:
data_GR<- toGRanges(data.bed)

data_annotated = annotate_regions(
  regions = data_GR,
  annotations = annotations,
  ignore.strand = TRUE,
  quiet = FALSE)
  
  annots_order = c(
  'hg19_genes_1to5kb',
  'hg19_genes_promoters',
  'hg19_genes_5UTRs',
  'hg19_genes_exons',
  'hg19_genes_intronexonboundaries',
  'hg19_genes_introns',
  'hg19_genes_3UTRs',
  'hg19_genes_intergenic')
  plot_annotation(annotated_regions = data_annotated,
                           annotation_order = annots_order)

and the I get:
Warning messages:
1: In subset_order_tbl(tbl = annotated_regions, col = "annot.type",  :
  There are elements in col_order that are not present in the corresponding column. Check for typos, or this could be a result of 0 tallies.
2: `distinct_()` was deprecated in dplyr 0.7.0.
and a barplot witht the bars haveing max height of around 27 instead of 8000.

Thank you for your time!
